#!/bin/bash

# Creates a TinyPilot installation bundle from the bundle/ folder.
# Fetches all required dependencies automatically.

# Exit on first error.
set -e

# Echo commands to stdout.
set -x

readonly REPO_TINYPILOT='https://github.com/tiny-pilot/tinypilot.git'
readonly REPO_ANSIBLE_TINYPILOT='https://github.com/tiny-pilot/ansible-role-tinypilot.git'
readonly REPO_ANSIBLE_NGINX='https://github.com/tiny-pilot/ansible-role-nginx'
readonly REPO_ANSIBLE_USTREAMER='https://github.com/tiny-pilot/ansible-role-ustreamer'

readonly BUNDLE_DIR='bundle'

pushd "${BUNDLE_DIR}"

git clone --depth 1 "${REPO_TINYPILOT}" tinypilot

git clone "${REPO_ANSIBLE_TINYPILOT}" ansible-role-tinypilot
# Use experimental branch with adjustments for this bundler.
pushd ansible-role-tinypilot
git checkout origin/experimental/with-bundler
popd

git clone --depth 1 "${REPO_ANSIBLE_NGINX}"

git clone --depth 1 "${REPO_ANSIBLE_USTREAMER}"

# Remove the `.git/` folders.
find . -type d -name ".git" | xargs rm -rf

popd

# Generate build output.
ls -lahR "${BUNDLE_DIR}" > dist/files.txt
tar \
  --create \
  --file dist/tinypilot.tar \
  --directory "${BUNDLE_DIR}" \
  .
