version: 2.1
jobs:
  check_whitespace:
    docker:
      - image: cimg/base:2021.04
    resource_class: small
    steps:
      - checkout
      - run:
          name: Check for trailing whitespace
          command: ./dev-scripts/check-trailing-whitespace
      - run:
          name: Check that all text files end in a trailing newline
          command: ./dev-scripts/check-trailing-newline
  check_bash:
    docker:
      - image: koalaman/shellcheck-alpine:v0.8.0
    steps:
      - run:
          name: Install dependencies needed to check out repo
          command: apk add bash git openssh-client grep
      - checkout
      - run:
          name: Run static analysis on bash scripts
          command: ./dev-scripts/check-bash
  build_bundle:
    docker:
      - image: debian:buster-20220527
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: apt-get update && apt-get install -y git libffi-dev libssl-dev python3-dev python3-venv wget
      - run:
          name: Create the bundle
          command: ./create-bundle
      - store_artifacts:
          path: dist/
workflows:
  version: 2
  test:
    jobs:
      - check_whitespace
      - check_bash
      - build_bundle
