#!/bin/bash

# Installs the TinyPilot software.

# Exit on first error.
set -e

# Exit on unset variable.
set -u

# Echo commands to stdout.
set -x

# Bootstrap environment for installation.
apt-get update --allow-releaseinfo-change-suite
apt-get install -y \
  git \
  libffi-dev \
  libssl-dev \
  python3-dev \
  python3-venv

python3 -m venv venv
. venv/bin/activate
pip install pip==21.3.1
pip install -r requirements.txt

ansible-playbook \
  --inventory localhost, \
  install.yml \
  --extra-vars "@settings.voyager.yml"

cp settings.voyager.yml /home/tinypilot/settings.yml
chown tinypilot:tinypilot /home/tinypilot/settings.yml
