#!/bin/bash

# Installs TinyPilot and all dependencies.

# Exit on first error.
set -e

# Exit on unset variable.
set -u

# Echo commands to stdout.
set -x

# Prevent installation on the 64-bit version of Raspberry Pi OS.
# https://github.com/tiny-pilot/tinypilot/issues/929
if [[ "$(uname -m)" == 'aarch64' && "$(lsb_release --id --short)" == 'Debian' ]]; then
  echo '64-bit Raspberry Pi OS is not yet supported.' >&2
  echo 'Please use the 32-bit version of Raspberry Pi OS.' >&2
  exit 1
fi

# Bootstrap environment for installation.
apt-get update --allow-releaseinfo-change-suite
apt-get install -y \
  git \
  libffi-dev \
  libssl-dev \
  python3-dev \
  python3-venv

python3 -m venv venv
. venv/bin/activate
pip install pip==21.3.1
pip install -r requirements.txt

ansible-playbook \
  --inventory localhost, \
  install.yml \
  --extra-vars "@settings.voyager.yml"

cp settings.voyager.yml /home/tinypilot/settings.yml
chown tinypilot:tinypilot /home/tinypilot/settings.yml
